### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by gdedi001** [pewinkel85/prj-rev-bwfs-dasmoto#1]
Fantastic job with your the overall structure of your HTML, as a developer I had no trouble looking through your code! Your website is filled with colorful headers and text that stands out in a meaningful way. There aren’t any outstanding areas to improve on, you went above and beyond for this! 

At least one recommendation would be to experiment with different font types. Familiarizing yourself with Google fonts is a great way to expand your knowledge as a developer. 
Visit [Google Fonts](https://fonts.google.com/)​​ for more detail. https://developers.google.com/fonts/docs/getting_started

**Comment by pewinkel85** [comment]
Thank you for the great tips and links! I will definitely use them!
